pt-BR:
  label_redmine_nikoca_re: "Niko-Niko"
  label_redmine_nikoca_re_full: "Calendário"
  project_module_redmine_nikoca_re: "Niko-Niko"
  permission_view_redmine_nikoca_re: "Navegar"
  permission_manage_redmine_nikoca_re: "Participar"
  label_conditions_new: "Conte-me como esta seu humor hoje?"
  comment_form: "Formulário para submeter comentários"
  field_user: "Usuário"
  field_date: "Data"
  field_feeling: "Humor"
  field_comment: "Comentários"
  good: "Bom"
  normal: "Normal"
  bad: "Ruim"
  no_comment: "(ainda não publicado)"
  comment_unit: " comentários"
  team_feeling: "Humor da equipe"
  item_select: "Por favor, selecione"
  caption_feeling: " Humor"
  caption_today_feeling: "Como esta seu humor hoje?"
  to_old: "retroceder"
  to_new: "avançar"
